Update socks-proxy-terminals-mac-chrome

diff --git a/socks-proxy-terminals-mac-chrome b/socks-proxy-terminals-mac-chrome
--- a/socks-proxy-terminals-mac-chrome
+++ b/socks-proxy-terminals-mac-chrome
@@ -36,3 +36,38 @@ Bash 3.2$ ssh -CX -i ~/Documents/aws/pem/id_rsa user@host /usr/bin/firefox
 NOTE: On a Windows machine, install Cygwin to get X11 capability
 NOTE: Still need to have the sudo ssh -i ~/id_rsa -p 443 -D 80 -g user@ipaddress port mapping working for the above commands to work.
 
+
+-----------------
+
+# Install and Config FoxyProxy
+Launch Firefox on the VM
+Go to about:addons and search for FoxyProxy Standard. Install it, then restart Firefox.
+Back in about:addons search for "My Add-ons." FoxyProxy Standard should now be installed.
+Click on Preferences
+Click Add New Proxy
+General tab:
+Proxy Name: somehostname:80
+Proxy Details tab:
+Host or IP Address: localhost 
+Port: 80
+SOCKS proxy?: (checked)
+SOCKS v5: (checked)
+URL Patterns tab:
+# create patterns with URL values of *internalhostname* (surrounded by the * symbols), whitelist these, and enable these patterns
+FoxyProxy Preferences Dialog, on any  tab:
+From the Select Mode dropdown, choose: "Use proxies based on their pre-defined patterns and priorities"
+
+----
+#!/bin/bash
+
+PID="`/usr/bin/pgrep -f '\<[s]sh .*-D 80'`"
+if [ -n "$PID" ]
+then
+  echo 'Aborting - one or more SOCKS5 proxies are already running.'
+  echo 'Process ID(s):' $PID'.'
+  exit 1
+else
+  echo -e "\n$HOSTNAME Running ${0##*/}."
+  sudo ssh -p 443 -D 80 -g user@host
+  echo -e "\n$HOSTNAME ${0##*/} done."
+fi
